---
seo_meta:
  name: Cybros
  description: Cybros
  keywords: []

# url_options:
#  host: 0.0.0.0:3000
#  protocol: http

admin:
  emails: ['guochunzhong@thape.com.cn', 'wangyue7@thape.com.cn', 'fengqiaorong@thape.com.cn', 'xuxiaohong@thape.com.cn', 'jasl9187@hotmail.com', 'zengrong@thape.com.cn','fangzixue@thape.com.cn','yexin@thape.com.cn']
